name: bitcoin-qa
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - requests
  - schedule
  - python-dotenv
  - pip:
      - openai>=1.12.0
      - tabulate
      - chainlit>=0.7.700
      - pydantic==1.10.13
      - typing-extensions
      - fastapi
      - uvicorn
      - starlette
      - anyio
